name: "base"
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - streamlit>=1.10.0
    - jupyter-server-proxy>=3.2.1
    - adaptivelcbin>=0.1.6
    - astropy!=3.0.*,!=3.1,!=3.1.1,>=2.0.12
    - astroquery 
    - beautifultable
    - black
    - cython
    -  git+https://git@github.com/ferrigno/pymosaics.git#egg=pymosaic_fits
    - git+https://github.com/oda-hub/oda_api.git#egg=oda_api
    - git+https://gitlab.astro.unige.ch/ferrigno/nustar-pipeline.git#egg=nustarpipeline
    - git+https://gitlab.astro.unige.ch/oda/api-clients/oda_api_wrapper.git#egg=oda-integral-wrapper
    - git+https://gitlab.astro.unige.ch/ferrigno/pysas.git#egg=pyxmmsas
    - emcee
    - ipympl
    - ipynbname
    - jupyter
    - jupyter_contrib_nbextensions
    - jupyterlab
    - matplotlib
    - notebook
    - nbconvert
    #- nlopt
    #- numba
    - numpy
    - optimalgrouping
    - pandas
    - papermill
    - photutils
    - pyfftw
    - Pygments
    - pyLCSIM
    - socketIO-client
    - stingray
prefix: "/opt/conda"
